/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-dim": "#060e20",
        "inverse-primary": "#006a6e",
        "tertiary-fixed": "#ff85e4",
        "on-background": "#dee5ff",
        "primary-fixed": "#00f4fe",
        "surface-container-highest": "#192540",
        "primary-fixed-dim": "#00e5ee",
        "surface-tint": "#a1faff",
        "error-container": "#9f0519",
        "secondary-fixed": "#dac9ff",
        "surface": "#060e20",
        "primary": "#a1faff",
        "on-secondary-fixed": "#40009b",
        "on-secondary-container": "#d9c8ff",
        "tertiary-fixed-dim": "#ff68e3",
        "on-surface-variant": "#a3aac4",
        "on-primary-fixed": "#004346",
        "surface-container": "#0f1930",
        "tertiary-container": "#ff05e5",
        "surface-container-high": "#141f38",
        "on-primary-container": "#00575b",
        "background": "#060e20",
        "inverse-on-surface": "#4d556b",
        "surface-bright": "#1f2b49",
        "error": "#ff716c",
        "on-error": "#490006",
        "secondary-container": "#5516be",
        "on-tertiary-container": "#1b0017",
        "on-tertiary": "#42003a",
        "error-dim": "#d7383b",
        "outline": "#6d758c",
        "secondary-dim": "#8455ef",
        "secondary-fixed-dim": "#ceb9ff",
        "secondary": "#ac8aff",
        "on-surface": "#dee5ff",
        "tertiary-dim": "#ff59e3",
        "primary-dim": "#00e5ee",
        "on-primary": "#006165",
        "outline-variant": "#40485d",
        "surface-container-low": "#091328",
        "on-error-container": "#ffa8a3",
        "inverse-surface": "#faf8ff",
        "surface-variant": "#192540",
        "tertiary": "#ff59e3",
        "on-secondary": "#280067",
        "surface-container-lowest": "#000000",
        "on-tertiary-fixed-variant": "#6d0061",
        "on-secondary-fixed-variant": "#5f28c8",
        "on-tertiary-fixed": "#33002d",
        "primary-container": "#00f4fe",
        "on-primary-fixed-variant": "#006266"
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
    },
  },
  plugins: [],
}
